version: '2'
services:
 da:
  image: antitree/private-tor
  #restart: always
  expose:
    - "7000"
    - "9030"
    - "54444"
  environment:
    ## set your Nickname here (only use letters and numbers)
    #TOR_NICKNAME: DA1
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
 relay:
  image: antitree/private-tor
  expose:
    - "7000"
    - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    - da
 exit:
  image: antitree/private-tor
  expose:
    - "7000"
    - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    - da
 client:
  image: antitree/private-tor
  ports:
    - "9050:9050"
  volumes:
    - ./tor:/tor
  environment:
    ROLE: CLIENT
  depends_on: 
    - da
