version: '2'
services:
 da1:
  image: antitree/private-tor
  #restart: always
  expose:
    - "7000"
    - "9030"
  environment:
    ## set your Nickname here (only use letters and numbers)
    #TOR_NICKNAME: DA1
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
 da2:
  image: antitree/private-tor
  #restart: always
  expose:
    - "7000"
    - "9030"
  environment:
    ## set your Nickname here (only use letters and numbers)
    #TOR_NICKNAME: DA1
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
 da3:
  image: antitree/private-tor
  #restart: always
  expose:
    - "7000"
    - "9030"
  environment:
    ## set your Nickname here (only use letters and numbers)
    #TOR_NICKNAME: DA1
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
 relay:
  image: antitree/private-tor
  expose:
    - "7000"
    - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
 exit:
  image: antitree/private-tor
  expose:
    - "7000"
    - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
 client:
  image: antitree/private-tor
  ports:
    # Setups a listener on host machine
    - "9050:9050"
    - "9051:9051"
  volumes:
    - ./tor:/tor
  environment:
    ROLE: CLIENT
  depends_on: 
    - da1
    - da2
    - da3

